apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m8j6kflde-nodejs
  janus-idp.io/tekton: m8j6kflde-nodejs
  backstage.io/kubernetes-id: m8j6kflde-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m8j6kflde-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
